import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/Componets/Shared/Header";
import Footer from "@/Componets/Shared/Footer";
import CartProvider from "@/context/CartProvider";
// Font Setup
const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
        <CartProvider>
          <Header />
          {children}
          <footer>
            <Footer />
          </footer>
        </CartProvider>
      </body>
    </html>
  );
}
